### ISSUE TITLE
请问这个源码到底是以什么协议开源的？如果需要付费，请不要滥用 MIT 协议。

### ISSUE THREAD

**Issue by GanterFengDavid** [dathlin/HslControlsDemo#9]
如题，如果需要付费，完全可以使用一个自定义的商用开源协议，没人反对付费。用了 MIT 协议，应当完全免费使用。

**Comment by dathlin** [comment]
本意是DEMO程序本身是MIT开源的，但是引用的库是付费的，对您造成的误解，抱歉。
